import { DataObject } from "../types/objects";

const data: DataObject[] = [
  {
    id: "1",
    username: "joe_black",
    firstname: "Joe",
    lastname: "Black",
    city: "Amsterdam",
    phone: +31612345678,
  },
  {
    id: "2",
    username: "mpkocak",
    firstname: "Mehmet Polat",
    lastname: "Koçak",
    city: "İstanbul",
    phone: +901234567889,
  },
  {
    id: "3",
    username: "jack_daniels",
    firstname: "Jack",
    lastname: "Daniels",
    city: "New York",
    phone: +11234567889,
  },
  {
    id: "4",
    username: "akntr",
    firstname: "Akın",
    lastname: "Tor",
    city: "İstanbul",
    phone: +904561237889,
  },
  {
    id: "5",
    username: "elessar",
    firstname: "Aragorn",
    lastname: "Son of Arathorn",
    city: "Minas Tirith",
    phone: +901237894556,
  },
  {
    id: "6",
    username: "greenleaf",
    firstname: "Legolas",
    lastname: "Son of Thranduil",
    city: "Mirkwood",
    phone: +303216549887,
  },
  {
    id: "7",
    username: "son_of_gondor",
    firstname: "Boromir",
    lastname: "Son of Denethor",
    city: "Minas Tirith",
    phone: +901237894556,
  },
  {
    id: "8",
    username: "master_dwarf",
    firstname: "Gimli",
    lastname: "Son of Glóin",
    city: "Ered Luin",
    phone: +201237894556,
  },
  {
    id: "9",
    username: "last_of_his_heir",
    firstname: "Theóden",
    lastname: "Son of Thengel",
    city: "Golden Hall",
    phone: +311237894556,
  },
  {
    id: "10",
    username: "loyal_son_of_rohan",
    firstname: "Eomer",
    lastname: "Son of Eomund",
    city: "Golden Hall",
    phone: +313214568779,
  },
  {
    id: "11",
    username: "captain_of_gondor",
    firstname: "Faramir",
    lastname: "Son of Denethor",
    city: "Minas Tirith",
    phone: +901239876556,
  },
];

export default data;
